FROM php:7.4-fpm

ENV LC_ALL C.UTF-8
ENV TERM xterm
ENV DEBIAN_FRONTEND=noninteractive

ARG USER_ID
ARG GROUP_ID
ARG XDEBUG_REMOTE_HOST
ARG XDEBUG_PORT
ARG XDEBUG_IDEKEY
ARG NODE_VERSION

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

RUN apt-get update && apt-get install -y \
        software-properties-common \
        apt-utils \
        curl \
        wget \
        unzip \
        libmcrypt-dev \
        libonig-dev \
        libicu-dev \
        libzip-dev \
        libxml2-dev \
        openssl \
        libpq-dev \
        librabbitmq-dev \
        iproute2 \
        git \
        npm \
    && pecl install amqp \
    && docker-php-ext-install -j$(nproc) bcmath pdo pdo_pgsql zip \
    && docker-php-ext-enable amqp

RUN echo "display_startup_errors = On \n \
        display_errors = On \n \
        error_reporting = E_ALL \n \
        memory_limit = 2048M \n \
        max_input_vars = 100000 \n \
        error_log = /var/log/php-fpm/error.log" > /usr/local/etc/php/conf.d/40-custom.ini \
    && pecl install xdebug \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so) \n \
        xdebug.client_host=$XDEBUG_REMOTE_HOST \n \
        xdebug.client_port=$XDEBUG_PORT \n \
        xdebug.idekey=$XDEBUG_IDEKEY \n \
        xdebug.start_with_request=yes \n \
        xdebug.mode=debug, develop \n \
        xdebug.log=/var/log/xdebug.log" > /usr/local/etc/php/conf.d/xdebug.ini

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN mkdir -p /.composer/cache/ && chown -vR ${USER_ID}:${GROUP_ID} /.composer

ENV NVM_DIR="/home/${USER_ID}/.nvm"
ARG USER_BASHRC="/home/${USER_ID}/.bashrc"

RUN apt-get update && apt-get install -y \
        source

RUN mkdir -p ${NVM_DIR} \
    && touch ${USER_BASHRC} \
    && chown -vR ${USER_ID}:${GROUP_ID} ${NVM_DIR} ${USER_BASHRC}

RUN set -x \
	&& echo "" >> ~/.bashrc \
	&& echo 'export NVM_DIR="/home/www/.nvm"' >> ~/.bashrc \
	&& echo '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm' >> ~/.bashrc

ENV PATH $PATH:/home/${USER_ID}/.node-bin

USER ${USER_ID}:${GROUP_ID}

RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash \
	&& mkdir -p $NVM_DIR \
	&& source $NVM_DIR/nvm.sh \
	&& nvm install ${NODE_VERSION} \
	&& nvm use ${NODE_VERSION} \
	&& nvm alias ${NODE_VERSION} \
	&& npm config set python $(which python2.7) \
	&& ln -s `npm bin --global` /home/www/.node-bin

RUN set -x \
	&& echo "" >> ~/.bashrc \
	&& echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.bashrc \
	#&& echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.bashrc_profile \
	#&& echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.profile \
	&& echo '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm' >> ~/.bashrc

WORKDIR /var/www

CMD ["php-fpm"]