parameters:
  app.microservice.http.config.uuid: '00000000-0000-0000-0000-000000000003'
  app.microservice.http.config.fields:
    field1: true
    field2: 123
    field3:
      - ['string1', 111]
      - ['string2', 222]
      - ['string3', 333]
