#index:
#    path: /
#    controller: App\Controller\DefaultController::index

http_microservice_get_config:
  path: /microservice/get/config
  # the controller value has the format 'controller_class::method_name'
  controller: App\Controller\BlogController::list