parameters:

imports:
    - { resource: microservice.rest.yml }
    - { resource: microservice.grpc.yml }
    - { resource: microservice.http.yml }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    microservice.rest.config_provider:
        class: App\Service\ConfigProvider\RestApiConfigProvider
        arguments:
            - '%app.microservice.rest.config.uuid%'
            - '%app.microservice.rest.config.fields%'

    microservice.grpc.config_provider:
        class: App\Service\ConfigProvider\GrpcConfigProvider
        arguments:
            - '%app.microservice.grpc.config.uuid%'
            - '%app.microservice.grpc.config.fields%'

    microservice.http.config_provider:
        class: App\Service\ConfigProvider\HttpConfigProvider
        arguments:
            - '%app.microservice.http.config.uuid%'
            - '%app.microservice.http.config.fields%'

    App\Service\ConfigProvider\Configurator:
        arguments:
            $configProviders:
                - '@microservice.rest.config_provider'
                - '@microservice.grpc.config_provider'
                - '@microservice.http.config_provider'

    #Symfony\Component\Form\FormBuilderInterface:

