parameters:

imports:
    - { resource: microservice.rest.yml }
    - { resource: microservice.grpc.yml }
    - { resource: microservice.http.yml }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    microservice.first_rest.config:
        class: App\Service\ConfigProvider\Microservices\RestApiMicroservice\Config
        arguments:
            - '%app.microservice.rest.config.uuid%'
            - '%app.microservice.rest.config.fields%'

    microservice.first_rest.config_adapter:
        class: App\Service\ConfigProvider\RestApiConfigProvider
        arguments:
            - '@microservice.first_rest.config'

    microservice.second_grpc.config:
        class: App\Service\ConfigProvider\Microservices\GrpcMicroservice\Config
        arguments:
            - '%app.microservice.grpc.config.uuid%'
            - '%app.microservice.grpc.config.fields%'

    microservice.second_grpc.config_adapter:
        class: App\Service\ConfigProvider\GrpcConfigProvider
        arguments:
            - '@microservice.second_grpc.config'

    microservice.third_http.config:
        class: App\Service\ConfigProvider\Microservices\HttpMicroservice\Config
        arguments:
            - '%app.microservice.http.config.uuid%'
            - '%app.microservice.http.config.fields%'

    microservice.third_http.config_adapter:
        class: App\Service\ConfigProvider\HttpConfigProvider
        arguments:
            - '@microservice.third_http.config'

    App\Service\ConfigProvider\ConfigManager:
        arguments:
            $configProviders:
                - '@microservice.first_rest.config_adapter'
                - '@microservice.second_grpc.config_adapter'
                - '@microservice.third_http.config_adapter'

